DSFR - a11Y - Frf/dsfr form builder setup
betagouv/rdv-service-public pull request #3577
Opened 2023-05-31 13:41 UTC by julieSalha

Pour tester : <`mettre ici l'url de la review app une fois déployé`>

Ticket lié : 
[Refonte DSFR - Page 'Votre compte' (changement de mail / mot de passe)#3575](https://github.com/betagouv/rdv-solidarites.fr/issues/3575)

Closes #3575 
# Checklist

Avant la revue :
- [x] Préparer des captures de l’interface avant et après : 
Avant (Bootstrap) : 
<img width="1397" alt="Capture d’écran 2023-05-31 à 15 44 28" src="https://github.com/betagouv/rdv-solidarites.fr/assets/49035942/4d2531ba-c087-43b5-bcea-090e861b788b">

Après (DSFR) : 
<img width="1440" alt="Capture d’écran 2023-05-31 à 15 44 35" src="https://github.com/betagouv/rdv-solidarites.fr/assets/49035942/152ba3fe-fc06-4f3f-81ad-ea84fcc58a3c">

- [x] Nettoyer les commits pour faciliter la relecture
- [x] Supprimer les éventuels logs de test et le code mort

Revue :
- [x] Relecture du code
- [ ] Test sur la review app / en local

2023-06-01 09:54 UTC, julieSalha commented
@francois-ferrandis pour faire le point sur la PR, les sujets que j'aimerais aborder avec toi : 
- [ ] Correction pour l'erreur détectée par Slim-lint
- [ ] Rendu non visible sur la [version déployée](https://demo-rdv-solidarites-pr3577.osc-secnum-fr1.scalingo.io/)

2023-06-01 12:40 UTC, francois-ferrandis requested changes
>     * [ ]  Correction pour l'erreur détectée par Slim-lint : `app/views/layouts/application_dsfr.html.slim:17 [W] ConsecutiveControlStatements: 3 consecutive control statements can be merged into a single `ruby:` filter`

Je t'ai répondu en commentaire. :wink: 

>     * [ ]  Rendu non visible sur la [version déployée](https://demo-rdv-solidarites-pr3577.osc-secnum-fr1.scalingo.io/)

Il y avait un bug chez Scalingo (voir [sur Mattermost](https://mattermost.incubateur.net/betagouv/threads/fergunthr7y8ibf4s47kip5qee)), c'est corrigé !

2023-06-01 12:40 UTC, francois-ferrandis commented on .slim-lint.yml
> +  - 'app/views/layouts/application_dsfr.html.slim'
En effet l'offence est pas bien utile je trouve.

Je te propose qu'on ajoute

```yaml
  ConsecutiveControlStatements:
    enabled: false
```
après la ligne 78 de ce fichier, pour ignorer globalement cette règle de lint.

En effet, si on ignore le fichier `application_dsfr.html.slim`, il ne sera plus analysé par le linter du tout.

2023-06-01 12:41 UTC, francois-ferrandis approved these changes
Je valide pour ne pas bloquer la PR après mon départ, mais mon commentaire sur .slim-lint.yml tient toujours. :handshake:

2023-06-01 13:53 UTC, julieSalha commented on .slim-lint.yml
> +  - 'app/views/layouts/application_dsfr.html.slim'
Merci François,  c'est mieux en effet :-)

2023-11-22 08:49 UTC, ousmanedev commented
Est-ce-que cette PR est toujours d'actualité ? @francois-ferrandis @julieSalha

2023-11-22 10:50 UTC, victormours commented
cette pr propose un changement d'interface avec des textes d'explications qui ne correspondent pas au fonctionnement de l'appli, alors que le scope d'origine était jsute de passer au dsfr.

2023-11-22 10:50 UTC, closed without merging