Renseigner la raison de la suppression dans les webhooks et les envoyer quand suppression pour RGPD
betagouv/rdv-service-public pull request #3825
Opened 2023-10-05 11:13 UTC by qblanc

Cette PR est nécessaire pour permettre à rdv-insertion de se mettre en conformité avec le RGPD, et pour éviter des asymétries d'informations entre les deux apps.

Cette PR ajoute un attr_accessor `action_source` aux modèles incluant `WebhookDeliverable`, permettant de renseigner le déclencheur de l'action (ici, des destroy), cette `action_source` étant ensuite transmises en tant que `trigger` dans les metadonnées du payload.
Elle active également l'envoi des webhooks lorsque des records sont supprimés pour cause de RGPD.

Légèrement hors scope de cette PR : lorsqu'un utilisateur supprime son compte sur rdv-solidarités, cela ne devrait pas le supprimer sur rdv-insertion. J'utilise donc le nouveau mécanisme pour flaguer ce cas de figure afin que nous le gèrerions correctement côté rdv-insertion.

2023-10-05 14:36 UTC, francois-ferrandis requested changes

2023-10-05 14:36 UTC, francois-ferrandis commented on spec/jobs/cron_job/destroy_old_rdvs_and_inactive_accounts_job_spec.rb
> +    end.to have_enqueued_job(WebhookJob).at_least(:once)
On aurait besoin d'un test qui vérifie qu'on inclue bien le nouveau champ avec la bonne valeur, j'ai cru le voir à `null` quand j'ai débuggé ce test.

2023-10-05 14:36 UTC, francois-ferrandis commented on spec/jobs/cron_job/destroy_old_rdvs_and_inactive_accounts_job_spec.rb
> +  end
C'est fait automatiquement entre chaque exemple donc pas nécessaire de le faire explicitement. :wink:

2023-10-05 14:36 UTC, francois-ferrandis commented on app/models/concerns/webhook_deliverable.rb
> +      trigger: action_source,
Est-ce qu'on peut n'avoir qu'un seul nom pour cette notion plutôt que d'avoir un nom internet un nom externe ? Que dis-tu de `reason` ?

2023-10-05 14:36 UTC, francois-ferrandis commented on app/jobs/cron_job.rb
> -        po.skip_webhooks = true
Je vois qu'après ce changement on n'utilise `skip_webhooks` pus qu'à un seul endroit... Peut-être pourrait-on se débarrasser bientôt de ce mécanisme ? (moins de code, plus de joie)

2023-10-05 15:26 UTC, victormours commented on app/models/concerns/webhook_deliverable.rb
> +      trigger: action_source,
ou même `webhook_reason` ou `webhook_source` pour qu'on comprenne facilement que cet attribut sert aux webhooks

2023-10-09 12:07 UTC, francois-ferrandis approved these changes
Ça m'a l'air bon !

Concernant l'impact  sur les autres consommateurs de webhooks, à priori ça passe, puisque c'est principalement utilisé pour afficher des RDVs sur les calendriers (Zimbra, Outlook), et donc les RDVs de plus de deux ans n'ont plus d'importance j'imagine.

2023-10-10 08:06 UTC, qblanc commented
Je passe cette PR en draft pour qu'elle ne soit pas mergée pour l'instant, le temps que l'on déploie l'adaptation de code nécessaire de notre côté (sinon cela nous fera supprimer des usagers que l'on ne veut pas supprimer).

2023-11-22 08:52 UTC, ousmanedev commented
@qblanc , 

Des nouvelles quant à cette PR ?

2023-11-22 09:33 UTC, qblanc commented
Oui ! J'étais en vacances c'est pour ça que ça a un peu traîné. Je pense qu'on est proche de la fin des A/R sur ma PR de notre côté, dès que c'est merge chez nous on pourra merge ici aussi !

2023-12-13 14:10 UTC, francois-ferrandis approved these changes
Ça m'a l'air bon à merger, qu'on avance là-dessus ! :rocket:

2023-12-13 14:10 UTC, francois-ferrandis commented on app/models/concerns/webhook_deliverable.rb
> +      webhook_reason: webhook_reason,
Dans une grand majorité des cas, cette valeur est `nil`, c'est OK pour vous ?

2023-12-13 14:34 UTC, qblanc commented on app/models/concerns/webhook_deliverable.rb
> +      webhook_reason: webhook_reason,
oui ce n'est pas un souci pour nous !

2023-12-13 14:41 UTC, merged